/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "UpstashRedisRestToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UpstashRedisRestUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "admin": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
  }
}
